name: mgenware_dart_lints
description: Dart lint rules used in Mgenware.
version: 5.0.0
homepage: https://github.com/mgenware/mgenware_dart_lints

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  lints: ^4.0.0
  flutter_lints: ^4.0.0
