name: mgenware_dart_lints
description: Dart lint rules used by Mgenware. It includes all official recommended Dart lint rules in `package:lints/recommended.yaml`.
version: 1.0.0
homepage: https://github.com/mgenware/mgenware_dart_lints

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  lints: ^1.0.1
