name: mgenware_dart_lints
description: Dart lint rules used in Mgenware.
version: 4.1.0
homepage: https://github.com/mgenware/mgenware_dart_lints

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1
